name: 'Install gofumpt'
description: 'Installs gofumpt for use in GitHub Actions'

author: 'Christian Budde <Christian.Budde@meko.de>'

inputs:
  gofumpt_version:
    description: 'Version of gofumpt to install'
    required: false
    default: 'latest'

outputs:
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22.2
        cache-dependency-path: "*/*.sum"

    - name: Set up Go workspace
      run: |
        mkdir -p $GITHUB_WORKSPACE/go/bin
        echo "$GITHUB_WORKSPACE/go/bin" >> $GITHUB_PATH
      shell: bash

    - name: Ensure cache directories exist
      run: |
        mkdir -p $HOME/go/pkg/mod
        mkdir -p $HOME/.cache/go-build
      shell: bash

    - name: Restore Go cache
      id: cache
      uses: actions/cache@v4
      if: "hashFiles('**/go.sum') != ''"
      with:
        path: |
          $HOME/go/pkg/mod_${{ github.run_id }}
          $HOME/.cache/go-build_${{ github.run_id }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-

    - name: Set GOBIN environment variable
      run: echo "GOBIN=$GITHUB_WORKSPACE/go/bin" >> $GITHUB_ENV
      shell: bash

    - name: Install gofumpt
      run: |
        if [ "${{ inputs.gofumpt_version }}" == "latest" ]; then
          go install mvdan.cc/gofumpt@latest
        else
          go install mvdan.cc/gofumpt@${{ inputs.gofumpt_version }}
        fi
      shell: bash

    - name: Save Go cache
      if: steps.cache.outputs.cache-hit != 'true' && always()
      uses: actions/cache@v4
      with:
        path: |
          $HOME/go/pkg/mod_${{ github.run_id }}
          $HOME/.cache/go-build_${{ github.run_id }}
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
