name: 'Install gofumpt'
description: 'Installs gofumpt for use in GitHub Actions'

author: 'Christian Budde <Christian.Budde@meko.de>'

inputs:
  gofumpt_version:
    description: 'Version of gofumpt to install'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22.2
        cache-dependency-path: "**/go.sum"

    - name: Set GOBIN and GOPATH environment variables
      run: |
        echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
      shell: bash

    - name: Add GOBIN to PATH
      run: echo "$(go env GOBIN)" >> $GITHUB_PATH
      shell: bash

    - name: Install gofumpt
      run: |
        if [ "${{ inputs.gofumpt_version }}" == "latest" ]; then
          go install mvdan.cc/gofumpt@latest
        else
          go install mvdan.cc/gofumpt@${{ inputs.gofumpt_version }}
        fi
      shell: bash
