name: 'Install gofumpt'
description: 'Installs gofumpt for use in GitHub Actions'

author: 'Christian Budde <Christian.Budde@meko.de>'

inputs:
  gofumpt_version:
    description: 'Version of gofumpt to install'
    required: false
    default: 'latest'

outputs:
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Restore Go modules cache
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ runner.tool_cache }}/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22.2
        cache-dependency-path: "**/go.sum"

    - name: Set GOBIN environment variable
      run: echo "GOBIN=${{ runner.tool_cache }}/go/bin" >> $GITHUB_ENV
      shell: bash

    - name: Install gofumpt
      run: |
        if [ "${{ inputs.gofumpt_version }}" == "latest" ]; then
          go install mvdan.cc/gofumpt@latest
        else
          go install mvdan.cc/gofumpt@${{ inputs.gofumpt_version }}
        fi
      shell: bash

    - name: Save Go modules cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache@v4
      with:
        path: ${{ runner.tool_cache }}/go/pkg/mod
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}