name: 'Install gofumpt'
description: 'Installs gofumpt for use in GitHub Actions'

author: 'Christian Budde <Christian.Budde@meko.de>'

inputs:
  gofumpt_version:
    description: 'Version of gofumpt to install'
    required: false
    default: 'latest'

outputs:
  cache-hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22.2
        cache-dependency-path: "*/*.sum"

    - name: Set up Go workspace
      run: |
        mkdir -p $GITHUB_WORKSPACE/go/bin
        echo "$GITHUB_WORKSPACE/go/bin" >> $GITHUB_PATH
      shell: bash

    - name: Restore Go cache
      id: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set GOBIN environment variable
      run: echo "GOBIN=$GITHUB_WORKSPACE/go/bin" >> $GITHUB_ENV
      shell: bash

    - name: Install gofumpt
      run: |
        if [ "${{ inputs.gofumpt_version }}" == "latest" ]; then
          go install mvdan.cc/gofumpt@latest
        else
          go install mvdan.cc/gofumpt@${{ inputs.gofumpt_version }}
        fi
      shell: bash

    - name: Save Go cache
      if: steps.cache.outputs.cache-hit != 'true'
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}