name: "Install gofumpt"
description: "Installs gofumpt for use in GitHub Actions"

author: "Christian Budde <Christian.Budde@meko.de>"

inputs:
  gofumpt_version:
    description: "Version of gofumpt to install"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Check if Go is installed
      id: check_go
      run: echo "go_installed=$(command -v go >/dev/null 2>&1 && echo true || echo false)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Install Go
      if: steps.check_go.outputs.go_installed != 'true'
      uses: actions/setup-go@v6
      with:
        go-version: ^1.22.2

    - name: Set GOBIN and GOPATH environment variables
      run: |
        echo "GOBIN=$(go env GOPATH)/bin" >> $GITHUB_ENV
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
      shell: bash

    - name: Add GOBIN to PATH
      run: echo "$(go env GOBIN)" >> $GITHUB_PATH
      shell: bash

    - name: Install gofumpt
      run: |
        if [ "${{ inputs.gofumpt_version }}" == "latest" ]; then
          go install mvdan.cc/gofumpt@latest
        else
          go install mvdan.cc/gofumpt@${{ inputs.gofumpt_version }}
        fi
      shell: bash
