name: Test gofumpt

on: [push]

jobs:
  setup-and-run-gofumpt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install gofumpt
        uses: ./
        with:
          gofumpt_version: 'latest'

      - name: Run gofumpt
        run: gofumpt -w .